# Site settings
name: 黄鑫成
location: 广东东莞
company: 
position: Java开发工程师
github: https://github.com/sundaydg
facebook: https://www.facebook.com/
phone: 13729975787
email: 641313426@qq.com

baseurl: ""

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

